---
- name: Prepare base system.
  hosts: localhost
  tasks:
    - include_tasks: ./roles/conan-deploy/tasks/prep.yml

- name: Install Conan Exiles
  hosts: localhost
  tasks:
    - include_tasks: ./roles/conan-deploy/tasks/exiles_install.yml
    - include_tasks: ./roles/conan-deploy/tasks/exiles_config.yml
    - include_tasks: ./roles/conan-deploy/tasks/exiles_mods.yml
    - include_tasks: ./roles/conan-deploy/tasks/exiles_service.yml
  handlers:
    - include_tasks: ./roles/conan-deploy/tasks/handlers.yml
