---
- name: Include secret variables.
  include_vars: ./roles/conan-deploy/vars/secrets.yml

- name: Include handlers.
  include_vars: 

- name: Create ConanSandbox mod temp directory.
  file:
    path: "/home/{{ conan_user }}/exiles/modtmp"
    state: directory
    owner: "{{ conan_user }}"
    group: "{{ conan_group }}"

- name: Create ConanSandBox mod directory.
  file:
    path: "/home/{{ conan_user }}/exiles/ConanSandbox/Mods"
    state: directory
    owner: "{{ conan_user }}"
    group: "{{ conan_group }}"

- name: Create modlist.txt from template.
  lineinfile:
    path: "/home/{{ conan_user }}/exiles/ConanSandbox/Mods/modlist.txt"
    owner: "{{ conan_user }}"
    group: "{{ conan_group }}"
    line: "*{{ item.path | basename }}"
    create: yes
  with_items:
    - "{{ mods_to_copy.files }}"
