---
- name: Include secret variables.
  include_vars: ./roles/conan-deploy/vars/secrets.yml

- name: Create ConanSandbox mod temp directory.
  file:
    path: "/home/{{ conan_user }}/exiles/modtmp"
    state: directory
    owner: "{{ conan_user }}"
    group: "{{ conan_group }}"

- name: Download mods from Steam workshop. This may take some time!
  command: "/usr/games/steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir /home/{{ conan_user }}/exiles/modtmp +login {{ steam_user }} {{ steam_password }} +workshop_download_item 440900 {{ item }} +exit"
  become: yes
  become_user: "{{ conan_user }}"
  with_items:
    - "{{ server_mod_ids }}"

- name: Gather all *.pak files found in the modtmp directory.
  find:
    path: "/home/{{ conan_user }}/exiles/modtmp"
    recurse: yes
    data: "*.pak"
    register: mods_to_copy

- name: Copy all mod files to the mod directory.
  copy:
    src: "{{ item.path }}"
    dest: "/home/{{ conan_user }}/exiles/ConanSandbox/Mods"
    owner: "{{ conan_user }}"
    group: "{{ conan_group }}"
