- name: Create ConanSandbox mod temp directory.
  file:
    path: "/home/{{ conan_user }}/exiles/modtmp"
    state: directory
    owner: "{{ conan_user }}"
    group: "{{ conan_group }}"

- name: Download mods from Steam workshop. This may take some time!
  command: "/usr/games/steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir /home/{{ conan_user }}/exiles/modtmp +login anonymous +workshop_download_item 443030 {{ item }} +exit"
  become: yes
  become_user: "{{ conan_user }}"
  with_items:
    - "{{ server_mod_ids }}"
