---
- name: Copy Conan Exiles startup script to the exiles directory.
  template:
    src: ./roles/conan-deploy/templates/start-server.sh.j2
    dest: "/home/{{ conan_user }}/exiles/start-server.sh"
    owner: "{{ conan_user }}"
    group: "{{ conan_group }}"
    mode: u+rwx

- name: Deploy Conan Exiles service unit.
  template:
    src: ./roles/conan-deploy/templates/conan-exiles.service.j2
    dest: /etc/systemd/system/conan-exiles.service

- name: Insert crontab to restart service at 0900 UTC every day.
  cron:
    name: conan exiles
    weekday: "*"
    hour: "9"
    minute: "0"
    user: root
    job: "systemctl restart conan-exiles.service"
    state: present

- name: Start the Conan Exiles service.
  systemd:
    name: conan-exiles.service
    state: started
    enabled: yes
    daemon_reload: yes