---
- name: Include variables.
  include_vars: ./roles/conan-deploy/defaults/main.yml

- name: Include secret variables.
  include_vars: ./roles/conan-deploy/vars/secrets.yml

- name: Create ConanSandbox mod temp directory.
  file:
    path: "/home/{{ conan_user }}/exiles/modtmp"
    state: directory
    owner: "{{ conan_user }}"
    group: "{{ conan_group }}"

- name: Create ConanSandBox mod directory.
  file:
    path: "/home/{{ conan_user }}/exiles/ConanSandbox/Mods"
    state: directory
    owner: "{{ conan_user }}"
    group: "{{ conan_group }}"

- name: Create modlist for server from template.
  lineinfile:
    path: "/home/{{ conan_user }}/modids.txt"
    owner: "{{ conan_user }}"
    group: "{{ conan_group }}"
    line: "{{ item }}"
    create: yes
  with_items:
    - "{{ server_mod_ids }}"
