---
- name: Copy Conan Exiles startup script to the exiles directory.
  template:
    src: ./roles/conan-deploy/templates/start-server.sh.j2
    dest: "/home/{{ conan_user }}/exiles/start-server.sh"
    owner: "{{ conan_user }}"
    group: "{{ conan_group }}"
    
# - name: Start Conan Exiles server.
#   systemd:
#     service: conan-exiles.service
#     state: started

# - name: Insert crontab to restart service at 0900 UTC every day.
#   cron:
#     name: conan exiles
#     weekday: "*"
#     hour: "9"
#     minute: "0"
#     user: root
#     job: "systemctl restart conan-exiles.service"
#     state: present
