---
- name: Include variables.
  include_vars: ./roles/conan-deploy/defaults/main.yml

- name: Get list of services installed on the system.
  service_facts:

- name: Stop Conan Exiles service if it's running.
  systemd:
    name: conan-exiles.service
    state: stopped
  when: "'conan-exiles.service' in services"
  
- name: Create Conan Exiles base directory.
  file:
    path: "/home/{{ conan_user }}/exiles"
    state: directory
    owner: "{{ conan_user }}"
    group: "{{ conan_group }}"

- name: Download Conan Exiles server from Steam. This may take some time!
  command: "/usr/games/steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir /home/{{ conan_user }}/exiles +login anonymous +app_update 443030 +exit"
  become: yes
  become_user: "{{ conan_user }}"


