---
- name: Create Conan Exiles base directory.
  file:
    path: "/home/{{ conan_user }}/exiles"
    state: directory
    owner: "{{ conan_user }}"
    group: "{{ conan_group }}"

- name: Download Conan Exiles server from Steam. This may take some time!
  command: "/usr/games/steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir /home/{{ conan_user }}/exiles +login anonymous +app_update 443030 +exit"
  become: yes
  become_user: "{{ conan_user }}"

- name: Deploy Conan Exiles service unit.
  template:
    src: ./roles/conan-deploy/templates/conan-exiles.service.j2
    dest: /etc/systemd/system/conan-exiles.service

- name: Configure SystemD for Conan Exiles server.
  systemd:
    name: conan-exiles.service
    enabled: yes
    daemon_reload: yes
