---
- name: Prepare system - Ubuntu/Debian.
  include_tasks: prep_ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Conan Exiles server.
  include_tasks: exiles_install.yml

- name: Deploy Conan Exiles mods.
  include_tasks: exiles_mods.yml

- name: Configure Conan Exiles server.
  include_tasks: exiles_config.yml
