---
- name: Prepare system - Ubuntu/Debian
  hosts: localhost
  tasks:
    - include_tasks: ./prep_ubuntu.yml
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Install Conan Exiles
  hosts: localhost
  tasks:
    - include_tasks: ./exiles_install.yml
    - include_tasks: ./exiles_config.yml
    - include_tasks: ./exiles_mods.yml
    - include_tasks: ./exiles_service.yml
  handlers:
    - include_tasks: ./handlers.yml
