- name: Install multiverse repository.
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu jammy multiverse
    state: present
    update_cache: true

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present
    update_cache: true

- name: Check if i386 architecture is installed already.
  shell: dpkg --print-foreign-architectures | grep i386
  register: i386_result
  ignore_errors: true

- name: Install i386 architecture.
  command: dpkg --add-architecture i386
  when: i386_result.rc >= 1

- name: Install packages.
  apt:
    name: ["lib32gcc-s1", "perl-modules", "curl", "lsof", "libc6-i386", "bzip2",
           "xvfb", "winbind", "fluxbox", "vnc4server"]
    state: present
    update_cache: true

- name: Auto-accept Steam license.
  debconf:
    name: "steam"
    question: "steam/question"
    value: "I AGREE"
    vtype: "select"

- name: Install package steamcmd.
  apt:
    name: steamcmd
    state: present

- name: Set up Conan group.
  group:
    name: "{{ conan_group }}"
    state: present

- name: Set up Conan user.
  user:
    name: "{{ conan_user }}"
    comment: ARK server user.
    group: "{{ conan_group }}"
    state: present

- name: Install WineHQ apt key.
  apt_key:
    url: https://dl.winehq.org/wine-builds/winehq.key
    state: present

- name: Add WineHQ repository.
  apt_repository:
    repo: deb https://dl.winehq.org/wine-builds/ubuntu/ jammy main
    update_cache: yes

- name: Install Wine stable.
  apt:
    name: [wine-stable]
    install_recommends: yes
    state: present

- name: Install additional Wine packages.
  apt:
    name: ["wine64", "wine32"]
    state: present

- name: Deploy VNC Server start script.
  file:
    src: ./roles/conan-deploy/files/vnc-server.sh
    dest: /usr/bin/vnc-server.sh
    owner: root
    group: root

- name: Deploy VNC Server service.
  template:
    src: ./roles/conan-deploy/templates/vnc-server.service.j2
    dest: /etc/systemd/system/vnc-server.service

- name: Configure SystemD for Conan Exiles server.
  systemd:
    name: vnc-server.service
    enabled: yes
    daemon_reload: yes
