- name: Include variables.
  include_vars: ./roles/conan-deploy/defaults/main.yml

- name: Install multiverse repository.
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu jammy multiverse
    state: present
    update_cache: true

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present
    update_cache: true

- name: Check if i386 architecture is installed already.
  shell: dpkg --print-foreign-architectures | grep i386
  register: i386_result
  ignore_errors: true

- name: Install i386 architecture.
  command: dpkg --add-architecture i386
  when: i386_result.rc >= 1

- name: Install packages.
  apt:
    name: ["lib32gcc-s1", "perl-modules", "curl", "lsof", "libc6-i386", "bzip2", "xvfb", "winbind", "rsyslog"]
    state: present
    update_cache: true

- name: Auto-accept Steam license.
  debconf:
    name: "steam"
    question: "steam/question"
    value: "I AGREE"
    vtype: "select"

- name: Install package steamcmd.
  apt:
    name: steamcmd
    state: present

- name: Set max socket buffer size.
  sysctl:
    name: net.core.rmem_max
    value: 268435456
    state: present
    reload: yes

- name: Set max socket buffer size.
  sysctl:
    name: net.core.wmem_max
    value: 268435456
    state: present
    reload: yes

- name: Set max socket buffer size.
  sysctl:
    name: net.core.rmem_default
    value: 268435456
    state: present
    reload: yes

- name: Set max socket buffer size.
  sysctl:
    name: net.core.wmem_default
    value: 268435456
    state: present
    reload: yes

- name: Set PAM nofile hard limit.
  pam_limits:
    domain: "*"
    limit_item: nofile
    limit_type: hard
    value: 1000000

- name: Set PAM nofile soft limit.
  pam_limits:
    domain: "*"
    limit_item: nofile
    limit_type: soft
    value: 1000000

- name: Set PAM session requirements.
  pamd:
    name: common-session
    module_path: pam_systemd.so
    type: session
    control: optional
    new_type: session
    new_control: required
    new_module_path: pam_limits.so
    state: after

- name: Set up Conan group.
  group:
    name: "{{ conan_group }}"
    state: present

- name: Set up Conan user.
  user:
    name: "{{ conan_user }}"
    comment: Conan Exiles server user.
    group: "{{ conan_group }}"
    state: present

- name: Install WineHQ apt key.
  apt_key:
    url: https://dl.winehq.org/wine-builds/winehq.key
    state: present

- name: Add WineHQ repository.
  apt_repository:
    repo: deb https://dl.winehq.org/wine-builds/ubuntu/ jammy main
    update_cache: yes

- name: Install Wine stable.
  apt:
    name: ["wine-stable"]
    install_recommends: yes
    state: present

- name: Install additional Wine packages.
  apt:
    name: ["wine64", "wine32"]
    state: present
