# General ARK configuration variables.
ark_server_name: "DMH"
ark_user: steam
ark_group: steam
ark_max_players: 40
ark_cluster_id: dmharkcluster

# The "tick" rate is the number of times per second the server updates the clients.
# Default is 30, but higher value may immprove rubber banding.
ark_server_tick_rate: 90

# The default maximum client bandwidth rates. Measured in bytes per second.
ark_server_internet_speed: 1048576
ark_server_max_client_rate: 1048576
ark_server_min_dynamic_rate: 6990
ark_server_max_dynamic_rate: 149796

# Crystal Isles specific spawn rate multipler.
ci_spawn_multiplier: 2.0

# CSV List of mod IDs for ARK.
ark_mod_ids: "1404697612,489596581,1565015734,821530042,1400323349,859198322,741203089,1380777369,2017186718,932816570,2008948402,1980529718,1639458270,2147192126,816908578,880871931,1266909337,670764308"

# List of maps to be run in the cluster. Must use proper Wildcard names for maps.
ark_server_maps:
- name: Aberration_P
  port: 7780
  query_port: 27019
  rcon_port: 24094
  enabled: true
- name: Gen2
  port: 7790
  query_port: 27029
  rcon_port: 24099
  enabled: true
- name: Fjordur
  port: 7792
  query_port: 27031
  rcon_port: 24100
  enabled: true
- name: LostIsland
  port: 7794
  query_port: 27033
  rcon_port: 24101
  enabled: true
- name: Valguero_P
  port: 7796
  query_port: 27035
  rcon_port: 24102
  enabled: true
- name: Ragnarok
  port: 7798
  query_port: 27037
  rcon_port: 24103
  enabled: true
